name: letter
description: An application to rent books.

version: 1.0.1+2

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  firebase_auth:
  google_sign_in:
  flutter_conditional_rendering:
  fluttertoast:
  cloud_firestore:
  quickblox_sdk:
  provider:
  geolocator:
  image_picker:
  image_cropper:
  qr_flutter:
  barcode_scan:
  share: '>=0.6.2+3 <2.0.0'
  timeago:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.2+1

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/img/icon.png"
  image_path_android: "assets/img/icon.png"
  adaptive_icon_background: "assets/img/background.png"
  adaptive_icon_foreground: "assets/img/foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Black.ttf